lib/src/widget/camera_picker.dart

pickFromCamera方法增加enableAudio可选参数，默认值为false，用于初始化CameraController，当enableAudio为false时，只使用拍照功能时，不会强制要求麦克风权限

support set enableAudio attr

---

README-ZH.md
README.md
lib/src/delegates/camera_picker_text_delegate.dart
lib/src/widgets/camera_picker.dart

✨ `enableTapRecording`

---

README-ZH.md
README.md
lib/src/widgets/camera_picker.dart
lib/src/widgets/camera_picker_viewer.dart

✨ `shouldAutoPreviewVideo`

---

lib/src/constants/constants.dart
lib/src/delegates/camera_picker_text_delegate.dart
lib/src/widgets/camera_picker.dart
lib/src/widgets/camera_picker_viewer.dart

Breaking change:
- `DefaultCameraPickerTextDelegate...` -> `CameraPickerTextDelegate...`
- More fields with semantics have been added to text delegates.

✨ Add full semantics support

---

lib/src/constants/type_defs.dart
lib/src/internals/methods.dart
lib/src/widgets/camera_picker_viewer.dart

🚑️ Fix `EntitySaveCallback`

---

lib/src/widgets/camera_picker.dart

Resolves #84 with it's another issue.

🚑️ Unify the method to push to the viewer

---

CHANGELOG.md
lib/src/constants/type_defs.dart
lib/src/widgets/camera_picker.dart
pubspec.yaml

https://github.com/fluttercandies/flutter_wechat_camera_picker/issues/96#issuecomment-1146672048

🚀 Allow the foreground builder to be used all the time

---

CHANGELOG.md
example/pubspec.yaml
lib/src/constants/type_defs.dart
lib/src/widgets/camera_picker.dart
pubspec.yaml

♻️ Break `ForegroundBuilder`

---

CHANGELOG.md
lib/src/states/camera_picker_state.dart
lib/src/widgets/camera_picker.dart
pubspec.yaml

🎨 Reexpose constructor

---

CHANGELOG.md
example/pubspec.yaml
lib/src/states/camera_picker_state.dart
pubspec.yaml

✨ Add torch flashlight support

---

CHANGELOG.md
example/pubspec.yaml
lib/src/states/camera_picker_state.dart
pubspec.yaml

🚸 Precache captured image for better experience

---

CHANGELOG.md
lib/src/constants/config.dart
lib/src/states/camera_picker_state.dart

CameraPickerConfig 新增 FlashMode，设置相机默认闪光灯模式

feat: CameraPickerConfig 新增 FlashMode，设置相机默认闪光灯模式。

---

CHANGELOG.md
lib/src/delegates/camera_picker_text_delegate.dart
pubspec.yaml

Hi team,
I want support Vietnamese language for this package, please review it.
Thank you.

Semantics with Vietnamese

---

CHANGELOG.md
README-ZH.md
README.md
lib/src/constants/config.dart
lib/src/states/camera_picker_state.dart
pubspec.yaml

✨ Add `minimumRecordingDuration`

---

CHANGELOG.md
example/pubspec.yaml
lib/src/states/camera_picker_state.dart
pubspec.yaml

Fixes #190, fixes https://github.com/fluttercandies/flutter_wechat_assets_picker/issues/480

🥅 Catch exceptions for controller methods

---

CHANGELOG.md
example/pubspec.yaml
lib/src/states/camera_picker_state.dart
pubspec.yaml

Handles exceptions if locking methods are failed

---

CHANGELOG.md
lib/src/states/camera_picker_state.dart

🚸 Prevent duplicate shooting actions

---

CHANGELOG.md
example/pubspec.yaml
lib/src/internals/methods.dart
lib/src/states/camera_picker_state.dart
lib/src/states/camera_picker_viewer_state.dart
pubspec.yaml

🥅 Wrap controller methods

---

lib/src/states/camera_picker_viewer_state.dart

🐛 Fix `onEntitySaving` not returned after called

---

CHANGELOG.md
example/pubspec.yaml
lib/src/states/camera_picker_state.dart
pubspec.yaml

🐛 Allows `wrapControllerMethod` to return nullable result
